
#define REPEAT0(f,arg)
#define REPEAT1(f,arg) REPEAT0(f,arg) f(0,arg)
#define REPEAT2(f,arg) REPEAT1(f,arg) f(1,arg)
#define REPEAT3(f,arg) REPEAT2(f,arg) f(2,arg)
#define REPEAT4(f,arg) REPEAT3(f,arg) f(3,arg)
#define REPEAT5(f,arg) REPEAT4(f,arg) f(4,arg)
#define REPEAT6(f,arg) REPEAT5(f,arg) f(5,arg)
#define REPEAT7(f,arg) REPEAT6(f,arg) f(6,arg)
#define REPEAT8(f,arg) REPEAT7(f,arg) f(7,arg)
#define REPEAT9(f,arg) REPEAT8(f,arg) f(8,arg)
#define REPEAT10(f,arg) REPEAT9(f,arg) f(9,arg)
#define REPEAT11(f,arg) REPEAT10(f,arg) f(10,arg)
#define REPEAT12(f,arg) REPEAT11(f,arg) f(11,arg)
#define REPEAT13(f,arg) REPEAT12(f,arg) f(12,arg)
#define REPEAT14(f,arg) REPEAT13(f,arg) f(13,arg)
#define REPEAT15(f,arg) REPEAT14(f,arg) f(14,arg)
#define REPEAT16(f,arg) REPEAT15(f,arg) f(15,arg)