#ifndef __CONF_USART_H__
#define __CONF_USART_H__

#define USART2_TX_GPIO_PORT GPIOD
#define USART2_TX_PIN LL_GPIO_PIN_5
#define USART2_RX_GPIO_PORT GPIOD
#define USART2_RX_PIN LL_GPIO_PIN_6

#endif