#ifndef __CONF_SPI_H__
#define __CONF_SPI_H__

#define SPI1_SCK_PIN 			LL_GPIO_PIN_5
#define SPI1_SCK_GPIO_PORT 		GPIOA
#define SPI1_MISO_PIN			LL_GPIO_PIN_6
#define SPI1_MISO_GPIO_PORT		GPIOA
#define SPI1_MOSI_PIN			LL_GPIO_PIN_7
#define SPI1_MOSI_GPIO_PORT		GPIOA

#define SPI2_SCK_PIN 			LL_GPIO_PIN_1
#define SPI2_SCK_GPIO_PORT 		GPIOD
#define SPI2_MISO_PIN			LL_GPIO_PIN_3
#define SPI2_MISO_GPIO_PORT		GPIOD
#define SPI2_MOSI_PIN			LL_GPIO_PIN_4
#define SPI2_MOSI_GPIO_PORT		GPIOD

#define SPI3_SCK_PIN 			LL_GPIO_PIN_10
#define SPI3_SCK_GPIO_PORT 		GPIOC
#define SPI3_MISO_PIN			LL_GPIO_PIN_11
#define SPI3_MISO_GPIO_PORT		GPIOC
#define SPI3_MOSI_PIN			LL_GPIO_PIN_12
#define SPI3_MOSI_GPIO_PORT		GPIOC

#endif