#ifndef CONF_SERCOM_H_INCLUDED
#define CONF_SERCOM_H_INCLUDED

#define SERCOM0_SPEED 115200UL
#define SERCOM0_GENERATOR GCLK_GENERATOR_3
#define SERCOM0_MUX EDBG_CDC_SERCOM_MUX_SETTING
#define SERCOM0_PAD0 EDBG_CDC_SERCOM_PINMUX_PAD0
#define SERCOM0_PAD1 EDBG_CDC_SERCOM_PINMUX_PAD1
#define SERCOM0_PAD2 EDBG_CDC_SERCOM_PINMUX_PAD2
#define SERCOM0_PAD3 EDBG_CDC_SERCOM_PINMUX_PAD3

#define SERCOM4_SPEED 4000000UL
#define SERCOM4_GENERATOR GCLK_GENERATOR_3
#define SERCOM4_MUX RF_SPI_SERCOM_MUX_SETTING
#define SERCOM4_PAD0 RF_SPI_SERCOM_PINMUX_PAD0
#define SERCOM4_PAD1 PINMUX_UNUSED
#define SERCOM4_PAD2 RF_SPI_SERCOM_PINMUX_PAD2
#define SERCOM4_PAD3 RF_SPI_SERCOM_PINMUX_PAD3

#define SERCOM5_SPEED 115200UL
#define SERCOM5_GENERATOR GCLK_GENERATOR_3
#define SERCOM5_MUX USART_RX_3_TX_2_XCK_3
#define SERCOM5_PAD0 PINMUX_UNUSED
#define SERCOM5_PAD1 PINMUX_UNUSED
#define SERCOM5_PAD2 EXT1_SPI_SERCOM_PINMUX_PAD2
#define SERCOM5_PAD3 EXT1_SPI_SERCOM_PINMUX_PAD3


#endif /* CONF_SERCOM_H_ */
